channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - packaging==23.2
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - typing-extensions==4.8.0
name: mlflow-env
